name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Aftman (GitHub Action)
      - uses: ok-nick/setup-aftman@v0.4.2

      # Install tools from aftman.toml
      - name: Install tools
        run: aftman install

      - name: Format check
        run: stylua --check .

      - name: Lint
        run: selene src
